# This file is used as a template for sealed secrets
apiVersion: v1
kind: Secret
metadata:
  name: ddclient-secret
  namespace: ddclient
  labels:
    app: ddclient
stringData:
  ddclient.conf: |
    protocol=cloudflare,
    use=web,
    web=https://domains.google.com/checkip,
    zone=domain.zone,
    ttl=1,
    login=cloudflare@login.email,
    password=CloudFlareAPIKey
    host.domain.xxx
