name: docker-build

on:
  workflow_dispatch:
  release: 
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          #context: .
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/orenzp/k8s-dyndnsclient:latest
            ghcr.io/orenzp/k8s-dyndnsclient:1.0.0
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
